### ISSUE TITLE
SplitsTreeApp_unix_6_3_3: java.lang.module.FindException: Module splitstreesix not found

### ISSUE THREAD

**Issue by alephreish** [husonlab/splitstree6#20]
Just downloaded the latest version for unix:

````
$ uname -a
Linux XXXX 5.15.0-102-generic #112~20.04.1-Ubuntu SMP Thu Mar 14 14:28:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
$ /opt/splitstree6/jre/bin/java --version
openjdk 20.0.2 2023-07-18
OpenJDK Runtime Environment (build 20.0.2+10)
OpenJDK 64-Bit Server VM (build 20.0.2+10, mixed mode)
$ SplitsTreeApp 
Error occurred during initialization of boot layer
java.lang.module.FindException: Module splitstreesix not found
````

`SplitsTreeCE_unix_6_3_1-beta` starts w/o an issue but it appears to have a bug when it comes to export to the vector formats.

**Comment by husonlab** [comment]
Thanks for the message. I have fixed the issue and am uploading new installers now. The new releases fixe some issues with vector formats. If problems remain, please let me know.

**Comment by alephreish** [comment]
Thanks for the swift response! The new version starts and the svg export works (if only a bit sluggish). The pdf export throws the following exception though:

````
$ SplitsTree
sh: 0: getcwd() failed: No such file or directory
Version   SplitsTree App (version 6.3.4, built 11 Apr 2024)
Author(s) Daniel H. Huson and David Bryant
License   Copyright (C) 2024. This program comes with ABSOLUTELY NO WARRANTY.
This is free software, licensed under the terms of the GNU General Public License, Version 3.
Sources available at: https://github.com/husonlab/splitstree6


(java:368350): Gtk-CRITICAL **: 19:45:09.816: gtk_window_resize: assertion 'height > 0' failed
Workflow: 14
Loaded: Taxa:  Characters: 
NNet algorithm: ActiveSet taxa: 87 time: 0.2s fit: 99.9% splits: 300
Splits
Nodes: 1,393, Edges: 2,484
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.apache.pdfbox@3.0.2/org.apache.pdfbox.pdmodel.PDDocument.<clinit>(PDDocument.java:95)
	at jloda_fx@1.0.0-SNAPSHOT/jloda.fx.util.SaveToPDF.apply(SaveToPDF.java:99)
	at jloda_fx@1.0.0-SNAPSHOT/jloda.fx.util.SaveToPDF.apply(SaveToPDF.java:83)
	at jloda_fx@1.0.0-SNAPSHOT/jloda.fx.dialog.ExportImageDialog.saveNodeAsImage(ExportImageDialog.java:86)
	at jloda_fx@1.0.0-SNAPSHOT/jloda.fx.dialog.ExportImageDialog.show(ExportImageDialog.java:73)
	at splitstreesix@1.0.0-SNAPSHOT/splitstree6.window.MainWindowPresenter.lambda$setupCommonMenuItems$46(MainWindowPresenter.java:477)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.controls/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1415)
	at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1368)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3985)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1891)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2709)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 47 more
````

**Comment by husonlab** [comment]
Please send me a file that produces that particular error and I will look into it...
